### ISSUE TITLE
create a readme file.

### ISSUE THREAD

**Issue by thezeeshann** [thezeeshann/todo-ts#1]

**Comment by DanielZhang111** [comment]
Can I get assigned?

**Comment by DanielZhang111** [comment]
I am working on this currently, do you have any contributers you would like to thank?

**Comment by thezeeshann** [comment]
@DanielZhang111 does not yet have any contributers

**Comment by DanielZhang111** [comment]
Would you like me to leave a space for you to add some, for future cases?

**Comment by thezeeshann** [comment]
@DanielZhang111 yeah sure plase

**Comment by DanielZhang111** [comment]
Alright

**Comment by DanielZhang111** [comment]
@thezeeshann i have submitted it, could you check? 
<img width="513" alt="image" src="https://github.com/thezeeshann/todo-ts/assets/146117946/3991c53f-23c8-413d-b6d8-2078bd8afc72">

**Comment by DanielZhang111** [comment]
Idk if it worked, I might've submitted it wrong, if you can't see it, I'll try again

**Comment by thezeeshann** [comment]
@thezeeshann bro You don't need to create a readme of my profile. Have to create a readme related to the project. you

**Comment by thezeeshann** [comment]
@DanielZhang111  create a readme for this project https://github.com/thezeeshann/todo-ts

**Comment by DanielZhang111** [comment]
Why was it closed? Oh ok I'll do that later

**Comment by DanielZhang111** [comment]
Why has it been in the "not participating?"
